spring:
  cache:
    type: caffeine
    caffeine:
      spec: "expireAfterWrite=600s"
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: investLab
  data:
    mongodb:
#      uri: mongodb://localhost:27017/InvestLab
      uri: mongodb+srv://investlab:investlab123@investlab.gphsjai.mongodb.net/InvestLab?retryWrites=true&w=majority

bff:
  url: http://ec2-34-226-163-14.compute-1.amazonaws.com:8000
#   url: localhost:8000
